humans:
    me:
        user_id: 372018022

wrangler:
    # This is the application that will run the bot wrangler program and listen
    # for commands from `humans` (above). This can be your personal account or
    # whatever you want. It won't use very many API calls.
    consumer_key: asdf
    consumer_secret: asdf
    access_key: asdf
    access_secret: asdf

main_app:
    # If you are using a One App Many Bots model, configure your main
    # application here.
    # See http://dghubble.com/blog/posts/twitter-app-write-access-and-bots/
    consumer_key: mkey
    consumer_secret: msecret

bots:
    # Bots should be listed according to their screen names. If "use_main" is
    # True, then omit the consumer_key and consumer_secret.
    # Bot names should be lowercase.
    thegifingbot:
        use_main: false
        consumer_key: consumer_key
        consumer_secret: consumer_secret
        access_key: access_key
        access_secret: access_secret
        user_id: 1234
